$DNA1 = 'ACGGGAGGACGGGAAAATTACTACGGCATTAGC';
$DNA2 = 'ATAGTGCCGTGAGAGTGATGTAGTA';
print $DNA1, "\n";
print $DNA2, "\n\n";
$DNA3 = "$DNA1$DNA2";
print "$DNA3\n\n";
$DNA4 = $DNA1 . $DNA2;
print "$DNA4\n\n";